name: Sample Composite Action
description: Sample Composite Action

inputs:
  sample1:
    required: false
    description: 'sample1'
  sample2:
    required: false
    description: 'sample2'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - if: ${{ inputs.sample1 }}
      run: |
        echo "sample1: ${{ inputs.sample1 }}"
      shell: bash

    - if: ${{ inputs.sample2 }}
      run: |
        echo "sample2: ${{ inputs.sample2 }}"
      shell: bash

